check:
  - thoth-build
  - thoth-precommit
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: cve-update-job
  registry-secret: thoth-station-thoth-pusher-secret
deploy:
  project-org: "thoth-station"
  project-name: "thoth-application"
  image-name: "cve-update-job"
  overlay-contextpath: "cve-update/overlays/test/imagestreamtag.yaml"
